acceptance_tests/features/step_definitions/AddReport.steps.rb, acceptance_tests/features/step_definitions/CaptureData.steps.rb, acceptance_tests/features/step_definitions/LoadPage.steps.rb, acceptance_tests/features/step_definitions/RequireUrl.steps.rb, acceptance_tests/features/step_definitions/ResetReport.steps.rb, apps/common/controllers/reset.js, apps/common/views/partials/navigation.html, apps/common/views/start-again.html, apps/rtm/controllers/removed.js, apps/rtm/index.js, apps/rtm/views/complete.html, apps/rtm/views/confirm.html
I have changed the url so that /report-terrorism is not needed any more. I have changed this in the relevant places such as the acceptance tests, templates and controllers.
=> Changed the url from /report-terrorism to just /.

.dockerignore, .eslintignore, .istanbul.yml, .jscsrc.json, package.json
- Added istanbul to scripts in package.json
- Added istanbul config yml file
- Added cover to pre-commit (package.json)
- Added coverage to ignore files (docker, eslint)
=> Added istanbul test coverage to project

apps/rtm/fields/index.js
* removed defaults
* reapplied trim and hyphens
=> RTMD-40 - removed default formatters from textareas

apps/rtm/fields/index.js
* removed superfluous field config
* removed implicit labels
=> RTMD-45 - updated fields.js

acceptance_tests/features/step_definitions/EditReport.steps.rb, apps/common/translations/src/en/buttons.json, apps/rtm/views/reports.html
* changed translation for button from Edit to Update
* updated acceptance test
=> RTMD-46 - updated Edit button

apps/rtm/controllers/confirm.js, apps/rtm/steps.js, test/unit/apps/rtm/controllers/confirm.js
* added backLink null to confirm step
* confirm controller redirects to /reports when no reports
=> RTMD-44 - removed back links

acceptance_tests/features/step_definitions/AddReport.steps.rb, apps/common/views/partials/summary-table.html, apps/rtm/controllers/confirm.js, apps/rtm/views/confirm.html
* loop over reports and fields to generate table
=> RTMD-28 - generate confirm page

.dockerignore
Modified .dockerignore to remove unknown references. 
Added missing references
- node_modules
- public
- apps/*/translations/*/default.json
- LICENSE.md
- README.md
- CONTRIBUTING.md
=> RTMD-39 - modified .dockerignore to remove unknown references.

Dockerfile, docker-compose.yml, package.json, run.sh
- update Dockerfile to aid caching of layers
- include nginx proxy service in docker-compose and config and link
- don't postinstall on production
- remove redis env vars from run.sh they are unneccessary
=> Resolves RTMD-48 Docker config

apps/rtm/fields/index.js, apps/rtm/translations/src/en/validation.json
* use regex to determine if valid url
=> RTMD-26 - validate url field

app.js
* move app init into i18n on ready callback
=> RTMD-75 - wait for translations to load before booting app

apps/rotm/controllers/confirm.js, config.js, services/email/index.js
- update the config for emails (used GRO as a template)
- add a path to the translations
- add a context to the translate function call
- remove some twoddle from the email service
- add some logging to the email to log errors
=> Fix the email translations and config

apps/rotm/controllers/reports.js, test/unit/apps/rotm/controllers/reports.js
* added super call to getValues to ensure values are persisted
* updated tests
=> bugfix - RTMD-80 - optional field data not persisted

config.js, services/email/index.js
The emails work perfectly well when I test it on a localhost server. But when on the dev server, it's not sending and the current set of logs aren't showing any errors. Hopefully this will add some visibility.
=> Add more logging to email

apps/rotm/fields/index.js
=> RTMD-83 - display radio buttons on new lines

apps/rotm/controllers/confirm.js, apps/rotm/fields/index.js, apps/rotm/translations/src/en/validation.json, apps/rotm/views/confirm.html, apps/rotm/views/partials/contact-details.html, test/unit/apps/rotm/controllers/confirm.js
* removed confirm controller getValues method - this is no longer required
* removed superfluous test
* refactored toggle panel into partial
=> bugfix RTMD-76 - contact details cleared on validation error

app.js
=> Revert "Log the headers"

apps/rotm/acceptance/features/confirm.js, apps/rotm/acceptance/pages/confirm.js, apps/rotm/acceptance/pages/confirmation.js, apps/rotm/confirm-step-config.js, apps/rotm/controllers/confirm.js, apps/rotm/index.js, apps/rotm/translations/src/en/pages.json, apps/rotm/views/confirm.html, assets/scss/app.scss, codecept.conf.js
Added confirm step using standard format
=> feature RTMD-91 - confirm step

apps/rotm/index.js
added emailUser: false to config
=> bugfix RTMD-106 - never email customer

apps/rotm/acceptance/features/contact-details.js, apps/rotm/acceptance/pages/contact-details.js, apps/rotm/fields.js, apps/rotm/translations/src/en/validation.json
added regex to accept certain special charaters - +=() and space
=> feature RTMD-107 - accept special characters

apps/rotm/acceptance/features/report.js, apps/rotm/acceptance/pages/report.js, apps/rotm/controllers/report.js, apps/rotm/translations/src/en/fields.json, apps/rotm/translations/src/en/validation.json, test/unit/apps/rotm/controllers/report.js
As per service request, description is now a required field if url is omitted. Added custom validation to description field, will throw required validation error if both url and description are left blank
=> Feature RTMD-116 - description field conditional validation

apps/rotm/acceptance/features/report.js, apps/rotm/acceptance/pages/report.js, apps/rotm/controllers/report.js, apps/rotm/translations/src/en/fields.json, apps/rotm/translations/src/en/validation.json, test/unit/apps/rotm/controllers/report.js
=> Revert "Feature RTMD-116 - description field conditional validation"

apps/rotm/translations/src/en/journey.json, apps/rotm/translations/src/en/pages.json
Updated service title from "Report online terrorist materials" to "Report online material promoting terrorism or extremism"
=> amend - RTMD-115 - updated service title

apps/rotm/controllers/report.js, apps/rotm/fields.js, test/unit/apps/rotm/controllers/report.js
If dependent condition is not met, field it not validated, but also the field isn't included in the session, resulting in a loss of data.
* removed dependent condition
* added custom validator in controller
=> bugfix - remove dependent

.gitignore, apps/rotm/translations/src/en/buttons.json
- .ignore was previously ignoring any files being added to the translations/src
- add buttons.json
=> Fix image button not showing

app.js, apps/rotm/behaviours/get-image.js, apps/rotm/behaviours/save-image.js, apps/rotm/fields.js, apps/rotm/index.js, apps/rotm/models/image-upload.js, apps/rotm/translations/src/en/fields.json, apps/rotm/translations/src/en/pages.json, apps/rotm/views/add-image.html, apps/rotm/views/image.html, assets/scss/app.scss, config.js, index.js, mock-apis.js, mocks/image-upload.js, package.json, test/index.js, test/unit/behaviours/get-image.js, test/unit/behaviours/save-image.js, test/unit/behaviours/skip-step.js, test/unit/models/image-upload.js
- validate the filename extension
- mock virus scan and S3 upload
- save image object to session
- render image data with data:url in view
=> Validate and Upload image to present image preview/thumb

apps/rotm/acceptance/features/confirmation.js
Since this just broke in right to rent, add a test to catch the same case here.
=> Add acceptance test coverage for submission

.gitignore, package.json
This will allow the use .env to load environment variables which will speed up development thanks to @lennym
=> upgrade to hof-build 1.6.0

apps/rotm/translations/src/en/buttons.json, apps/rotm/views/check-your-report.html
=> Amend /check-your-report button

.drone.yml, .gitignore
=> Make sure containers link to the correct container names

.drone.yml
echo values to see what url is being tested
=> echo smoke test values

.drone.yml
And not redis and the app containers, which are not present in the build step
=> remove selenium container after use

.drone.yml
- Make smoke_test build job execute when event is trigger and environment is smoke_test
=> Set smoke_test job deployment events on smoke_test environment

.drone.yml
- Make smoke_test build job execute when event is trigger and environment is smoke_test
=> Set smoke_test job deployment events on smoke_test environment (#157)

apps/rotm/acceptance/features/thumbnail-alt-text.js, apps/rotm/views/check-your-report.html
* This is on `/check-your-report` step
=> [Rtmd 180] - thumbnail alt text

index.js
- Add redirect to express middleware to redirect /report to root page.
=> SD-68 - Redirect /report to root page

.drone.yml
**Jira Ticket**: https://collaboration.homeoffice.gov.uk/jira/browse/SD-127
**Changes**: Updated drone.yaml file to version 1
=> SD-127: Updated drone to version 1.0

.drone.yml
- Increased node image version in drone file from 8 to 14
=> Update node version

.drone.yml, config.js, package.json, test/_features/rotm/rotm.feature, test/_features/step_definitions/steps.js, test/_features/test.setup.js, test/setup.js, yarn.lock
**What?**
Adding acceptance tests using playwright/cucumber to test user journey including file uploads.
**Why?**
So that all subsequent changes can be tested against the desired journey path.
**How?**
.drone.yml , config.js and package.json file settings have been changed in line with similar setup in BRP. 'test' directory has been added which contains all test .js and .feature files.
**Testing?**
linting test run before commit.
=> Add acceptance tests to ROTM

.drone.yml
**Changes**	
- Added installation of playwright into acceptance_tests_uat step on drone.yaml file to resolve pipeline error when running acceptance tests.
=> ROTM-29: Installing playwright onto UAT branch

.drone.yml
**Changes**
- Updated drone.yaml with the correct URL for the UAT environment.
=> ROTM-29: Changed URL for acceptance tests

.snyk, apps/rotm/views/accessibility.html, apps/rotm/views/evidence-upload-confirm.html
Update accessibility statement wording for the ROTM form - [HOFF-772](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-772)
To correctly reflect the accessibility testing review that was done against WCAG 2.2
=> HOFF-772: Update ROTM Accessibility Statement

.snyk, apps/rotm/views/accessibility.html
Update Accessibility statement, please see ticket [ROTM-121](https://collaboration.homeoffice.gov.uk/jira/browse/ROTM-121)
As per business requirements
Updated the accessibility.html file as per business requirements
- [] I have written tests (if relevant)
=> [ROTM 121] update accessibility statement

.snyk, package.json, yarn.lock
[ROTM-137](https://collaboration.homeoffice.gov.uk/jira/browse/ROTM-137) -  Updated to latest HOF version
- Prevent bugs in future development
- Updated dependancies for ROTM
Tested on local machine 
=> ROTM-137 Updated to latest HOF version
