.dockerignore, Dockerfile, app.js, config.js, docker-compose.yml, docker/nginx/Dockerfile, docker/nginx/LICENSE, docker/nginx/nginx-local-dev.conf, docker/nginx/nginx.conf, docker/nginx/run.sh, run.sh
The environment can be accessed by running "docker-compose up" in the
project's root directory.
The environment attempts to mimic the production envirmonment.
In the local dev environment there is a single nginx container that
acts as a reverse proxy for three node containers running the app. The
node containers connect to a single redis container.
In the production environment three pods, each comprising of a nginx
container and a node container, connect to a single redis pod.
=> Add a local dev environment based on docker-compose

config.js
This commit fixes a bug where an env var set to the string "false" will
be added to the config object 'as is'. i.e. As the string "false" which
is a truthy value in javascript. The new behaviour instead converts it
to a boolean.
=> Correctly parse the boolean env vars

app.js
Added :-
- app.set('trust proxy', 1);
to app.js.
This allows an Express app to have knowledge that it's sitting behind a proxy and that the X-Forwarded-* header fields may be trusted.
as described in the link below
http://expressjs.com/en/guide/behind-proxies.html
=> RTMD-51 - made app trust proxy

package.json
This needs to have the `src/` on the end or it will throw when it finds .js files in the parent directory.
=> Fix path for shared translation files

package.json
The [Software Package Data Exchange](https://spdx.org/) defines a standard format for
machine-readable licence data. Previously, we were using a non-standard
identifier for the GPLv2; this commit amends it to adhere to the
standard.
Node's package manager complains about the invalid SPDX expression when building the app;
by fixing this we get rid of the warning.
=> Use valid SPDX licence expression

apps/rotm/behaviours/save-image.js, package.json, test/unit/behaviours/save-image.js
When validation errors are thrown they display with a message "Please fix the following error". If saving the file to file vault has failed, then there is nothing the user can "fix" to make it work, so displaying a validation message is not appropriate, and an application error should be displayed.
As an aside, the validation error is broken anyway as validation errors need to be passed in the form 
```
next({
key1: new ValidationError(...),
key2: new ValidationError(...)
});
```
(yes, this is both nasty and a little counterintuitive, but it's so you can throw multiple validation errors per step)
=> Don't use ValidationError for file-vault failures

apps/rotm/acceptance/features/check-your-report.js, apps/rotm/index.js, apps/rotm/translations/src/en/pages.json, apps/rotm/views/check-your-report.html
Adds the uploaded image to the check answers screen.
Outstanding issues not in the scope of the ticket:
* How does a user delete an image that they've previously uploaded without adding a new one?
=> Add image thumbnail on confirm page

apps/rotm/models/image-upload.js, mocks/image-upload.js, test/unit/models/image-upload.js
* The correct property name for file-vault uploads is "document" (see https://github.com/UKHomeOffice/file-vault/blob/master/controllers/file.js#L116)
* The URLs returned should not contain a bearer token
=> Fix file vault params

index.js
At the moment the config is being defined in config.js but then not actually used anywhere. Pass the config defined into hof so it is used in place of defaults for session store configuration.
=> Pass redis config into hof

package.json
Now we have headless chrome, we don't need to disable csp to run the acceptance tests
=> Remove dev:ci npm script

.drone.yml
Tests are running after deploy, before pods have restarted on the kube cluster
=> wait for deploy to finish before running tests

apps/rotm/acceptance/features/tab-focus.js, apps/rotm/views/image.html, assets/js/index.js, package.json
* Some hidden elements should not have tab focus.  This is for screenreader and normal users.   It is confusing.
* There are different items hidden when JS is enabled and disabled.  This deals with both scenarios
=> [RTMD-179] - Accessibility: remove tab focus for hidden elements

apps/rotm/translations/src/en/pages.json, apps/rotm/views/content/source.md, apps/rotm/views/source.html
- Move the helpful content in the image alt text to the main body
- If it's useful then it should be for all users otherwise remove it
- It's not just for screenreader users
=> [RTMD-181] - Move image alt content from /source

package.json
- Getting a linting error because hof-theme-govuk was not listed in dependencies. Now added.
=> Add hof-theme-govuk to package.json

apps/rotm/fields.js, apps/rotm/translations/src/en/fields.json
What?
An update that adds validators to 3 fields.
Why?
Users were able to submit urls through name field which could be identified as a phishing risk to HO employees.
Testing?
Tested locally, no issues.
Anything Else?
Locally I have a default.json file that lives in rotm/translations/en that responds positively only when edited with the validation error messages. Changing only the fields.json file with the validation error messages does not seem to output the respective validation error message and only outputs the generic 'There is a problem'.
=> SD-107: field validators & their respective validation error messages 

package.json
**What**
Upgraded hof-middlware to v2.2.4
**Why**
Applications using this library could be vulnerable to a redirection exploit where an attacker can use a Home Office page to redirect someone to their malicious site
**How**
In hof-middleware ensure URLs are relative paths – i.e. they start with a single / character. Absolute URLs starting with // will be rejected.
**Test**
Unit test and manual url test
=> Upgraded hof-middlware to v2.2.4 to fix redirection to malicious site

kube/file-vault-deployment.yaml, kube/file-vault-ingress.yaml, kube/ingress-external.yaml
Use latest filevault image that is tested and we know is working. Need to coordinate with caseworkers first before merging and deploying to ensure we don't unintentionally block access to them for previously submitted application images.
=> Revert to new filevault image

kube/app/ingress-external.yml
**What?**
Changed the UAT hostname.
**Why?**
The hostname previously given is in a different format.
**How?**
When requesting rotm-uat namespace through acp, I asked for _rotm.uat.internal.sas-notprod.homeoffice.gov.uk_ as the domain name instead of _report-terrorist-material.uat.internal.sas-notprod.homeoffice.gov.uk_
=> host name changed

.drone.yml
Enable CUCUMBER_PUBLISH_TOKEN to be consumed in drone.yml so that cucumber reports are published to the collection https://reports.cucumber.io/report-collections/1af00bc1-c58b-4b45-8fd8-ac69ff335d3c
=> ROTM-32-publish-cucumber-reports

.snyk, apps/rotm/views/evidence-upload-confirm.html
Add alternative text to images that are uploaded on the ROTM form - [HOFF-678](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-678)
To resolve an accessibility issue identified from tests using the WAVE tool
Before adding alternative text:
After adding alternative text:
=> HOFF-678: Add alt text to ROTM image upload

.snyk, kube/file-vault/file-vault-deployment.yml, yarn.lock
**What**
Implement error handling in file vault for HTTP response codes in the 4xx and 5xx range returned from the ClamAV REST service. [HOFF-780](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-780)
**Why**
HTTP response codes in the 4xx and 5xx range from the ClamAV REST service are not checked, which poses a security risk, as files that have not been properly scanned due to misconfiguration or downtime of the ClamAV service could be falsely marked as safe and uploaded to the storage, potentially allowing malicious files to bypass our security measures.
**How**
Check for http response status codes that are greater than or equal to 400 and raise an error.
**Test**
Testing in branch and UAT
=> HOFF-780 - File-vault update - Implement error handling in file vault for HTTP response codes

config.js, server.js, yarn.lock
Updated Feedback link. See ticket [ROTM 109](https://collaboration.homeoffice.gov.uk/jira/browse/ROTM-109)
per business request to allow users to complete the latest version of the feedback form
There are two parts:
1. Added a new environment variable "FEEDBACK_URL" in the HOF services config repo and allocated different urls based on environment. See [PR 426](https://github.com/UKHomeOfficeForms/hof-services-config/pull/426)
2. Updated the ROTM service to use the new environment variable by updating the config.js and server.js.
Ensure all unit and integration tests are passing
=> [ROTM 109] Update link to feedback form

bin/deploy.sh
we need to lock down the external UAT to home office network/POISE only - it should not be available to the public
[https://uat.notprod.report-terrorist-material.homeoffice.gov.uk/] is accessible to public
Change deploy.sh scripts to allow the deployment to have an external ingress (https://github.com/UKHomeOffice/rotm/commit/0e904f8648b349611e433c5a413754f640fe7d34)
Will check manually after redeployment
=> ROTM-128 adding ext ingress to service so it can read the white list
